# User config
author: "PORTFOLIO"
tagline: "PORTFOLIO"
description: ""
keywords: "Pineapple, Pineapple Pizza, Pineapple House"
email: "heairin1008@naver.com"
linkedin: "https://www.linkedin.com/"
twitter: "https://twitter.com/"
github: "https://github.com/heairin1008"

# Site config
baseurl: ""
highlighter: rouge
sass:
  sass_dir: assets/scss
  style: compressed
